# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BCTROAPI
                                 A QGIS plugin
 Links to Buchanan Computing TRO API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-29
        copyright            : (C) 2020 by Buchanan Computing
        email                : patryk.janicki@buchanancomputing.co.uk
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load BCTROAPI class from file BCTROAPI.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .TRO_API import BCTROAPI
    return BCTROAPI(iface)
