# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BCTROAPI
                                 A QGIS plugin
 Links to Buchanan Computing TRO API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2020-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Buchanan Computing
        email                : patryk.janicki@buchanancomputing.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication
from qgis.PyQt.QtGui import QIcon
from qgis.PyQt.QtWidgets import QAction, QMessageBox
#from qgis.core import QgsProject
import requests
#from PyQt5.QtWidgets import QAction, QMessageBox
from qgis.core import (QgsCoordinateReferenceSystem,
                       QgsCoordinateTransform,
                       QgsProject,
                       QgsRectangle,
                       QgsPointXY,
                       QgsGeometry,
                       QgsVectorLayer,
                       QgsFeature)
from qgis.gui import QgsMapTool
from qgis.utils import iface
# Initialize Qt resources from file resources.py
from .resources import *
# Import the code for the dialog
from .TRO_API_dialog import BCTROAPIDialog
import os.path
import json
from PyQt5.QtCore import *
from PyQt5.QtGui import *

from qgis.gui import QgsMapToolEmitPoint

class BCTROAPIMAP:
    """QGIS Plugin Implementation."""
    def run(self):
        """Run method that performs all the real work"""
        #Tool click
        #tool = PointTool(iface.mapCanvas())
        #iface.mapCanvas().setMapTool(tool)
		print ("Get Coords Click")

class PointTool(QgsMapTool):
    def __init__(self, canvas):
        QgsMapTool.__init__(self, canvas)
        self.canvas = canvas
        cursor = QCursor()
        cursor.setShape(Qt.WhatsThisCursor)
        #iface.mainWindow().centralWidget().setCursor(cursor)

    def canvasPressEvent(self, event):
        pass

    def canvasMoveEvent(self, event):
        x = event.pos().x()
        y = event.pos().y()

        point = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)

    def canvasReleaseEvent(self, event):
        #Get the click
        x = event.pos().x()
        y = event.pos().y()

        point = self.canvas.getCoordinateTransform().toMapCoordinates(x, y)
        print ("Click at {}".format(point))
    def activate(self):
        pass

    def deactivate(self):
        pass

    def isZoomTool(self):
        return False

    def isTransient(self):
        return False

    def isEditTool(self):
        return True
