# -*- coding: utf-8 -*-
"""
/***************************************************************************
 BCTROAPIDialog
                                 A QGIS plugin
 Links to Buchanan Computing TRO API
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2020-09-29
        git sha              : $Format:%H$
        copyright            : (C) 2020 by Buchanan Computing
        email                : patryk.janicki@buchanancomputing.co.uk
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets
from .resources import *
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'TRO_API_dialog_base.ui'))


class BCTROAPIDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(BCTROAPIDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        #self.setWindowFlags(Qt.WindowStaysOnTopHint)
        #self.Areacombobox.addItem('Cumbria')
        self.Formatcombobox.addItem('BCNATIVE')
        self.Formatcombobox.addItem('TRO-D')
        self.Formatcombobox.addItem('APDS')
        self.RadiusSlider.valueChanged.connect(self.changeValue)
        self.RadiusVal.setText(str(self.RadiusSlider.value()))
        self.Projectioncombobox.addItem('EPSG:27700')
        self.Projectioncombobox.addItem('EPSG:3857')
        #self.Projectioncombobox.addItem('EPSG:4326')
        #self.GetCoordsButton.clicked.connect(super(BCTROAPIDialog, self).getcoords())

    def changeValue(self, value):
        self.RadiusVal.setText(str(value))
